Dict in C: src/dict_buckets_dtor.c File Reference
dict_buckets_dtor.c File Reference
#include <stdlib.h>
#include "dict.h"
Functions
static void dict_bucket_dtor (bucket_t *bucket)
static void dict_bucket_dtor_with_entries (bucket_t *bucket, free_value_t free_value)
void dict_buckets_dtor (bucket_t **buckets, uint64_t size, int free_entry, free_value_t free_value)
Function Documentation
dict_bucket_dtor()
static void dict_bucket_dtor (bucket_t * bucket) static
Definition at line 12 of file dict_buckets_dtor.c.
{
    bucket_t *next = NULL;
    while (NULL != bucket) {
        next = bucket->next;
        free(bucket);
        bucket = next;
    }
}
References s_bucket::next.
Referenced by dict_buckets_dtor().
dict_bucket_dtor_with_entries()
static void dict_bucket_dtor_with_entries (bucket_t * bucket, free_value_t free_value) static
Definition at line 24 of file dict_buckets_dtor.c.
{
    bucket_t *next = NULL;
    while (NULL != bucket) {
        next = bucket->next;
        if (NULL != free_value)
            free_value(bucket->entry);
        free(bucket);
        bucket = next;
    }
}
References s_bucket::entry, and s_bucket::next.
Referenced by dict_buckets_dtor().
dict_buckets_dtor()
void dict_buckets_dtor (bucket_t ** buckets, uint64_t size, int free_entry, free_value_t free_value)
Definition at line 37 of file dict_buckets_dtor.c.
{
    uint64_t index = 0;
    for (; index < size; ++index) {
        if (1 == free_entry)
            dict_bucket_dtor_with_entries(buckets[index], free_value);
        else
            dict_bucket_dtor(buckets[index]);
    }
}
References dict_bucket_dtor(), and dict_bucket_dtor_with_entries().
Referenced by dict_buckets_ctor(), dict_dtor(), and dict_resize().