Dict in C: src/dict_bucket_delete.c File Reference
dict_bucket_delete.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "dict.h"
Functions
static int dict_bucket_delete_until (bucket_t *node, char *key, free_pair_t free_pair)
Deletes the node of a bucket once it has been identified by the key.
int dict_bucket_delete (bucket_t **bucket, char *key, free_pair_t free_pair)
Deletes an entry from the bucket based on the key.
Function Documentation
dict_bucket_delete()
int dict_bucket_delete (bucket_t ** bucket, char * key, free_pair_t free_pair)
Deletes an entry from the bucket based on the key.
If no node matched the key, -1 is returned as an error and the bucket is unchanged.
Warning
If a NULL pointer is passed for either the bucket or the key, the function will crash.
Note
The key is not marked as const as it may get free'd by the free_pair function, but bear in mind the current function will not modify the key.
If the free_pair function is a NULL pointer, it's not called. It may be useful if neither the key nor the value were allocated.
Parameters
bucket The bucket from which to remove the entry.
key The key used to match the entry to be removed.
free_pair The function called to release the key and value memory.
Returns
0 on success, -1 on error.
Definition at line 47 of file dict_bucket_delete.c.
{
    bucket_t *node = *bucket;
    if (!DICT_KEY_MATCH(node->key, key))
        return dict_bucket_delete_until(node, key, free_pair);
    *bucket = node->next;
    if (NULL != free_pair)
        free_pair(node->key, node->value);
    free(node);
    return 0;
}
References dict_bucket_delete_until(), DICT_KEY_MATCH, s_bucket::key, s_bucket::next, and s_bucket::value.
Referenced by dict_delete().
dict_bucket_delete_until()
static int dict_bucket_delete_until (bucket_t * node, char * key, free_pair_t free_pair) inline static
Deletes the node of a bucket once it has been identified by the key.
If no node matched the key, -1 is returned as an error and the bucket is unchanged.
Note
The key is not marked as const as it may get free'd by the free_pair function, but bear in mind the current function will not modify the key.
Parameters
node The bucket's front node from which to delete the entry.
key The key used to match the entry to delete.
free_pair The function used to release the key and value memory.
Returns
0 on success, -1 on error.
Definition at line 27 of file dict_bucket_delete.c.
{
    bucket_t *prev = NULL;
    while (NULL != node->key) {
        if (!DICT_KEY_MATCH(node->key, key)) {
            prev = node;
            node = node->next;
            continue;
        }
        dprintf(2, "Prev K : %s | Node K : %s | Next K : %s\n", prev->key, node->key, node->next->key);
        prev->next = node->next;
        if (NULL != free_pair)
            free_pair(node->key, node->value);
        free(node);
        return 0;
    }
    return -1;
}
References DICT_KEY_MATCH, s_bucket::key, s_bucket::next, and s_bucket::value.
Referenced by dict_bucket_delete().