Dict in C: src/dict_buckets_ctor.c File Reference
dict_buckets_ctor.c File Reference
#include <stdlib.h>
#include "dict.h"
Functions
int dict_buckets_ctor (bucket_t **buckets, uint64_t size)
Function Documentation
dict_buckets_ctor()
int dict_buckets_ctor (bucket_t ** buckets, uint64_t size)
Definition at line 11 of file dict_buckets_ctor.c.
{
    uint64_t index = 0;
    for (; index < size; ++index) {
        buckets[index] = (bucket_t *) calloc(1, sizeof(bucket_t));
        if (NULL == buckets[index]) {
            dict_buckets_dtor(buckets, index, NULL);
            return -1;
        }
    }
    return 0;
}
References dict_buckets_dtor().
Referenced by compute_new_buckets(), and dict_ctor().