Dict in C: src/dict_resize.c File Reference
dict_resize.c File Reference
#include <stdlib.h>
#include <string.h>
#include "dict.h"
#include "murmurhash1.h"
Functions
static bucket_t ** compute_new_buckets (uint64_t new_size)
This function is reponsible for allocating a new linked list buckets array.
static void dict_rehash_bucket (const bucket_t *bucket, bucket_t **new_buckets, uint64_t new_size)
This function iterates over a non-empty bucket linked list. It looks for all it's entries, re-hash the keys and tries to place the entry to a new bucket.
static uint64_t round_size (uint64_t new_size)
int dict_resize (dict_t *dict)
Function Documentation
compute_new_buckets()
static bucket_t ** compute_new_buckets (uint64_t new_size) static
This function is reponsible for allocating a new linked list buckets array.
If it fails, it deallocates all the successfully allocated linked list along with the buckets array itself, and it returns a NULL pointer.
Parameters
new_size The number of buckets to allocate.
Returns
The allocated buckets array on success, NULL pointer on error.
Definition at line 24 of file dict_resize.c.
{
    bucket_t **new_buckets = calloc(new_size, sizeof(bucket_t *));
    if (NULL == new_buckets)
        return NULL;
    if (-1 == dict_buckets_ctor(new_buckets, new_size)) {
        free(new_buckets);
        return NULL;
    }
    return new_buckets;
}
References dict_buckets_ctor().
Referenced by dict_resize().
dict_rehash_bucket()
static void dict_rehash_bucket (const bucket_t * bucket, bucket_t ** new_buckets, uint64_t new_size) static
This function iterates over a non-empty bucket linked list. It looks for all it's entries, re-hash the keys and tries to place the entry to a new bucket.
If the new bucket was not allocated, the function will crash. The buckets array must have been allocated using the dict_buckets_ctor function, which itself allocates all the subsequent linked list, so that the new_bucket is never a NULL pointer.
Parameters
bucket The bucket from which to scan for entries.
new_buckets The linked list buckets array receiving the entries.
new_size The linked list buckets array size.
Definition at line 52 of file dict_resize.c.
{
    uint32_t key_hash = 0;
    bucket_t **new_bucket = NULL;
    while (NULL != bucket && NULL != bucket->key) {
        key_hash = murmurhash1(bucket->key, strlen(bucket->key), HASH_SEED);
        new_bucket = &(new_buckets[DICT_BUCKET_IDX(key_hash, new_size)]);
        dict_bucket_insert(new_bucket, bucket->key, bucket->value);
        bucket = bucket->next;
    }
}
References DICT_BUCKET_IDX, dict_bucket_insert(), HASH_SEED, s_bucket::key, murmurhash1(), s_bucket::next, and s_bucket::value.
Referenced by dict_resize().
dict_resize()
int dict_resize (dict_t * dict)
Definition at line 81 of file dict_resize.c.
{
    uint64_t index = 0;
    uint64_t new_size = round_size(dict->size * DICT_RESIZE_FACTOR);
    bucket_t **new_buckets = compute_new_buckets(new_size);
    if (NULL == new_buckets)
        return -1;
    for (; index < dict->size; ++index)
        dict_rehash_bucket(dict->buckets[index], new_buckets, new_size);
    dict_buckets_dtor(dict->buckets, dict->size, NULL);
    free(dict->buckets);
    dict->buckets = new_buckets;
    dict->size = new_size;
    return 0;
}
References s_dict::buckets, compute_new_buckets(), dict_buckets_dtor(), dict_rehash_bucket(), DICT_RESIZE_FACTOR, round_size(), and s_dict::size.
Referenced by dict_insert().
round_size()
static uint64_t round_size (uint64_t new_size) static
https://github.com/python/cpython/blob/main/Python/hashtable.c#L108
Definition at line 70 of file dict_resize.c.
{
    uint64_t i = 1;
    if (new_size < DICT_MIN_SIZE)
        return DICT_MIN_SIZE;
    while (i < new_size)
        i <<= 1;
    return i;
}
References DICT_MIN_SIZE.
Referenced by dict_resize().