Dict in C: include/dict.h File Reference
dict.h File Reference
#include <stdint.h>
Data Structures
struct s_bucket
The bucket type is a linked list node which contains both the key and the value to store.
struct s_dict
This structure represents the state of a dict (hashmap) object. Upon insertion, the string keys are hashed using Murmurhash1 algorithm. They are then stored inside a linked list (bucket), inside an array (buckets).
struct s_dict_keys
This structure represents the keys of the dict. It will be computed each time the dict_keys() function is called. It will not be used by other function to operate on the dict, as the internal dict state is known by all functions.
struct s_dict_values
This structure represents the values of the dict. It will be computed each time the dict_values() function is called. It will not be used by other function to operate on the dict, as the internal dict state is known by all functions.
Macros
#define DICT_MIN_SIZE (2 << 3)
The default number of buckets to be allocated.
#define DICT_HIGH 0.5
The factor limit to be reach before allocating new buckets.
#define DICT_LOW 0.1
The factor limit to be reach before deallocating buckets.
#define DICT_RESIZE_FACTOR 2.0 / (DICT_HIGH + DICT_LOW)
Once multiplied by the number of entries, returns the new dict size.
#define DICT_MUST_GROW(D)
Returns whether the dict must grow to accept new entries.
#define DICT_MUST_SHRINK(D)
Returns whether the dict must shirnk to save some memory upon entry removal.
#define HASH_SEED 0
The hash seed to use. Mostly for security, but it has to be the same all across the project.
#define DICT_BUCKET_IDX(H, S)
Returns the index to the bucket in which to store the entry.
Typedefs
typedef void(* free_pair_t) (char *key, void *value)
Such function prototype represents the function to use to release the memory allcoated to an entry value. If the value was not allocated (e.g. the value is an integer), then you may use a NULL pointer instead to indicate that the value has not to be free.
typedef struct s_bucket bucket_t
The bucket type is a linked list node which contains both the key and the value to store.
typedef struct s_dict dict_t
This structure represents the state of a dict (hashmap) object. Upon insertion, the string keys are hashed using Murmurhash1 algorithm. They are then stored inside a linked list (bucket), inside an array (buckets).
typedef struct s_dict_keys dict_keys_t
This structure represents the keys of the dict. It will be computed each time the dict_keys() function is called. It will not be used by other function to operate on the dict, as the internal dict state is known by all functions.
typedef struct s_dict_values dict_values_t
This structure represents the values of the dict. It will be computed each time the dict_values() function is called. It will not be used by other function to operate on the dict, as the internal dict state is known by all functions.
Functions
int dict_buckets_ctor (bucket_t **buckets, uint64_t size)
Allocates new buckets linked list inside the array.
void dict_buckets_dtor (bucket_t **buckets, uint64_t size, free_pair_t free_pair)
Deallocates buckets linked list from the array.
int dict_bucket_has_key (const bucket_t *bucket, const char *key)
Returns whether a key is present in the bucket.
int dict_bucket_insert (bucket_t **bucket, char *key, void *value)
Inserts an entry into a dict bucket.
void dict_buckets_debug (bucket_t *const *buckets, uint64_t size)
This function prints the content of each linked list bucket from the buckets array.
dict_t * dict_ctor (void)
Allocates a new dict.
void dict_dtor (dict_t *dict, free_pair_t free_pair)
Deallocates the dict.
int dict_insert (dict_t *dict, char *key, uint64_t key_length, void *value)
Insert an entry into the dict.
int dict_resize (dict_t *dict)
Resizes the dict.
dict_keys_t * dict_get_keys (const dict_t *dict)
Returns the list of the keys of the dict.
void dict_free_keys (dict_keys_t *dict_keys)
Release memory from dict_get_keys allocations.
dict_values_t * dict_get_values (const dict_t *dict)
Returns the list of the values of the dict.
void dict_free_values (dict_values_t *dict_values)
Release memory from dict_get_values allocations.
Macro Definition Documentation
DICT_BUCKET_IDX
#define DICT_BUCKET_IDX (H, S)
Value:
(H) % (S)
Returns the index to the bucket in which to store the entry.
Parameters
H The key hash.
S The size of the buckets array.
Definition at line 68 of file dict.h.
Referenced by dict_insert(), and dict_rehash_bucket().
DICT_HIGH
#define DICT_HIGH 0.5
The factor limit to be reach before allocating new buckets.
Definition at line 23 of file dict.h.
DICT_LOW
#define DICT_LOW 0.1
The factor limit to be reach before deallocating buckets.
Definition at line 29 of file dict.h.
DICT_MIN_SIZE
#define DICT_MIN_SIZE (2 << 3)
The default number of buckets to be allocated.
Definition at line 17 of file dict.h.
Referenced by dict_ctor(), and round_size().
DICT_MUST_GROW
#define DICT_MUST_GROW (D)
Value:
((float) (D)->items / (float) (D)->size) > DICT_HIGH
Returns whether the dict must grow to accept new entries.
Parameters
D The dict to evaluate.
Definition at line 43 of file dict.h.
Referenced by dict_insert().
DICT_MUST_SHRINK
#define DICT_MUST_SHRINK (D)
Value:
((float) (D)->items / (float) (D)->size) < DICT_LOW
Returns whether the dict must shirnk to save some memory upon entry removal.
Parameters
D The dict to evaluate.
Definition at line 52 of file dict.h.
DICT_RESIZE_FACTOR
#define DICT_RESIZE_FACTOR 2.0 / (DICT_HIGH + DICT_LOW)
Once multiplied by the number of entries, returns the new dict size.
Definition at line 35 of file dict.h.
Referenced by dict_resize().
HASH_SEED
#define HASH_SEED 0
The hash seed to use. Mostly for security, but it has to be the same all across the project.
Definition at line 59 of file dict.h.
Referenced by dict_insert(), and dict_rehash_bucket().
Typedef Documentation
bucket_t
typedef struct s_bucket bucket_t
The bucket type is a linked list node which contains both the key and the value to store.
dict_keys_t
typedef struct s_dict_keys dict_keys_t
This structure represents the keys of the dict. It will be computed each time the dict_keys() function is called. It will not be used by other function to operate on the dict, as the internal dict state is known by all functions.
dict_t
typedef struct s_dict dict_t
This structure represents the state of a dict (hashmap) object. Upon insertion, the string keys are hashed using Murmurhash1 algorithm. They are then stored inside a linked list (bucket), inside an array (buckets).
Upon key insertion, if the number of items is greater than half the size, the buckets array is enlarged and all the key hashes are re-computed.
Upon key deletion, if the number of items is lower than the DICT_MIN_SIZE value, the buckets array is reduced and all the key hashes are re-comupted.
If a key is inserted twice, it's entry is overwritten to store the new value associated to that key. If the entry value was already allocated, the memory will not be released correctly, unless the programmer does it before using the same key twice (or more).
dict_values_t
typedef struct s_dict_values dict_values_t
This structure represents the values of the dict. It will be computed each time the dict_values() function is called. It will not be used by other function to operate on the dict, as the internal dict state is known by all functions.
free_pair_t
typedef void(* free_pair_t) (char *key, void *value)
Such function prototype represents the function to use to release the memory allcoated to an entry value. If the value was not allocated (e.g. the value is an integer), then you may use a NULL pointer instead to indicate that the value has not to be free.
Definition at line 76 of file dict.h.
Function Documentation
dict_bucket_has_key()
int dict_bucket_has_key (const bucket_t * bucket, const char * key)
Returns whether a key is present in the bucket.
Warning
If a NULL pointer is passed for bucket, the function will crash.
Note
If the key is NULL a falsy value may be returned. Make sure it's not before calling the function.
Parameters
bucket The bucket in which to look for the key.
key The key to look for in the bucket.
Returns
1 if present, 0 if not present.
Definition at line 11 of file dict_bucket_has_key.c.
{
    while (NULL != bucket->key) {
        if (bucket->key == key || 0 == strcmp(bucket->key, key))
            return 1;
        bucket = bucket->next;
    }
    return 0;
}
References s_bucket::key, and s_bucket::next.
Referenced by dict_insert().
dict_bucket_insert()
int dict_bucket_insert (bucket_t ** bucket, char * key, void * value)
Inserts an entry into a dict bucket.
Warning
If a NULL pointer is passed for bucket, the function will crash.
Note
If it failed to allocate the linked list bucket node, the bucket is left unchanged and the function returns -1.
Parameters
bucket The pointer to the allocated bucket.
key The key of the pair.
value The value of the pair.
Returns
0 on success, -1 on error.
Definition at line 11 of file dict_bucket_insert.c.
{
    bucket_t *node = (bucket_t *) calloc(1, sizeof(bucket_t));
    if (NULL == node)
        return -1;
    node->key = key;
    node->value = value;
    node->next = *bucket;
    *bucket = node;
    return 0;
}
References s_bucket::key, s_bucket::next, and s_bucket::value.
Referenced by dict_insert(), and dict_rehash_bucket().
dict_buckets_ctor()
int dict_buckets_ctor (bucket_t ** buckets, uint64_t size)
Allocates new buckets linked list inside the array.
If it failed to allocate one bucket, it free all the previously allocated ones before returning -1.
If existing buckets are already allocated inside the array, they will not be free by this function. The programmer will have to free them first, even though the purpose of this function is to allocate buckets of a new buckets array that has just been allocated.
Warning
If the buckets array is a NULL pointer, the function will crash.
Parameters
buckets The pre-allocated buckets array.
size The number of buckets to allocate inside the buckets array.
Returns
0 on success, -1 on error.
Definition at line 11 of file dict_buckets_ctor.c.
{
    uint64_t index = 0;
    for (; index < size; ++index) {
        buckets[index] = (bucket_t *) calloc(1, sizeof(bucket_t));
        if (NULL == buckets[index]) {
            dict_buckets_dtor(buckets, index, NULL);
            return -1;
        }
    }
    return 0;
}
References dict_buckets_dtor().
Referenced by compute_new_buckets(), and dict_ctor().
dict_buckets_debug()
void dict_buckets_debug (bucket_t *const * buckets, uint64_t size)
This function prints the content of each linked list bucket from the buckets array.
Warning
If NULL pointer is passed, or if the size is greater than the actual size of the array, this function will crash.
Note
The debugging content will be flushed to the stderr file descriptor.
Parameters
buckets The buckets to debug.
size The number of bucket inside the buckets array.
Definition at line 31 of file dict_buckets_debug.c.
{
    uint64_t index = 0;
    for (; index < size; ++index)
        print_bucket(buckets[index], index);
}
References print_bucket().
dict_buckets_dtor()
void dict_buckets_dtor (bucket_t ** buckets, uint64_t size, free_pair_t free_pair)
Deallocates buckets linked list from the array.
Warning
If the buckets array is a NULL pointer, the function will crash.
Note
This function will not free the buckets array, just it's elements.
Parameters
buckets The pre-allocated buckets array.
size The nuber of buckets to deallocate from the buckets array.
free_pair The function to use to free pair, may be NULL.
Definition at line 41 of file dict_buckets_dtor.c.
{
    uint64_t index = 0;
    for (; index < size; ++index)
        dict_bucket_dtor(buckets[index], free_pair);
}
References dict_bucket_dtor().
Referenced by dict_buckets_ctor(), dict_dtor(), and dict_resize().
dict_ctor()
dict_t * dict_ctor (void)
Allocates a new dict.
Note
If it failed, returns a NULL pointer.
Returns
The allocated dict.
Definition at line 11 of file dict_ctor.c.
{
    dict_t *dict = (dict_t *) calloc(1, sizeof(dict_t));
    if (NULL == dict)
        return NULL;
    dict->buckets = (bucket_t **) calloc(DICT_MIN_SIZE, sizeof(bucket_t *));
    if (NULL == dict->buckets || \
        -1 == dict_buckets_ctor(dict->buckets, DICT_MIN_SIZE)) {
        free(dict);
        return NULL;
    }
    dict->items = 0;
    dict->size = DICT_MIN_SIZE;
    return dict;
}
References s_dict::buckets, dict_buckets_ctor(), DICT_MIN_SIZE, s_dict::items, and s_dict::size.
dict_dtor()
void dict_dtor (dict_t * dict, free_pair_t free_pair)
Deallocates the dict.
The free_pair function will be in charge to free the key of the pair, if not constant, and the value, if not constant. If both are constant, you can pass a NULL pointer as nothing has to be free'd.
Warning
If a NULL pointer is passed, or if the dict has already been deallocated, the function will crash.
Parameters
dict The dict's pointer to deallocate.
free_pair The function to use to free pair, may be NULL.
Definition at line 11 of file dict_dtor.c.
{
    dict_buckets_dtor(dict->buckets, dict->size, free_pair);
    free(dict->buckets);
    free(dict);
}
References s_dict::buckets, dict_buckets_dtor(), and s_dict::size.
dict_free_keys()
void dict_free_keys (dict_keys_t * dict_keys)
Release memory from dict_get_keys allocations.
If a NULL pointer is passed, or if the dict keys have already been deallocated, the function will crash.
Parameters
dict_keys The keys to free.
Definition at line 11 of file dict_free_keys.c.
{
    free(dict_keys->keys);
    free(dict_keys);
}
References s_dict_keys::keys.
dict_free_values()
void dict_free_values (dict_values_t * dict_values)
Release memory from dict_get_values allocations.
If a NULL pointer is passed, or if the dict values have already been deallocated, the function will crash.
Parameters
dict_values The values to free.
Definition at line 12 of file dict_free_values.c.
{
    free(dict_values->values);
    free(dict_values);
}
References s_dict_values::values.
dict_get_keys()
dict_keys_t * dict_get_keys (const dict_t * dict)
Returns the list of the keys of the dict.
If an error occured during the dict_keys_t object allocation, NULL pointer is returned.
The dict_keys_t object will have to be free using the dict_free_keys function.
Warning
If a NULL pointer is passed, or if the dict has already been deallocated, the function will crash.
DO NOT TRY TO FREE ANY ITEM INSIDE THE keys MEMBER BY YOURSELF. The keys array member contains references to the keys, not copies. If you free one of them, it may break the whole dict object.
Note
The list of keys is not ordered. The keys are taken from each bucket from 0 to the size of the dict, and each of the bucket is iterated over from head to tail (linked list). Knowing that the insertion depends on a hash, we don't know the order in which the keys will appear in the list.
Parameters
dict The dict from which to get the keys.
Returns
The list of keys.
Definition at line 35 of file dict_get_keys.c.
{
    dict_keys_t *keys = (dict_keys_t *) calloc(1, sizeof(dict_keys_t));
    if (NULL == keys)
        return NULL;
    keys->keys = (const char **) calloc(dict->items, sizeof(char *));
    if (NULL == keys->keys) {
        free(keys);
        return NULL;
    }
    populate_keys(dict, keys);
    return keys;
}
References s_dict::items, s_dict_keys::keys, and populate_keys().
dict_get_values()
dict_values_t * dict_get_values (const dict_t * dict)
Returns the list of the values of the dict.
If an error occured during the dict_values_t object allocation, NULL pointer is returned.
The dict_values_t object will have to be free using the dict_free_values function.
Warning
If a NULL pointer is passed, or if the dict has already been deallocated, the function will crash.
DO NOT TRY TO FREE ANY ITEM INSIDE THE values MEMBER BY YOURSELF. The values array member contains references to the values, not copies. If you free one of them, it may break the whole dict object.
Note
The list of values is not ordered. The values are taken from each bucket from 0 to the size of the dict, and each of the bucket is iterated over from head to tail (linked list). Knowing that the insertion depends on a hash, we don't know the order in which the values will appear in the list.
Parameters
dict The dict from which to get the values.
Returns
The list of values.
Definition at line 35 of file dict_get_values.c.
{
    dict_values_t *values = (dict_values_t *) calloc(1, sizeof(dict_values_t));
    if (NULL == values)
        return NULL;
    values->values = (const void **) calloc(dict->items, sizeof(void *));
    if (NULL == values->values) {
        free(values);
        return NULL;
    }
    populate_values(dict, values);
    return values;
}
References s_dict::items, populate_values(), and s_dict_values::values.
dict_insert()
int dict_insert (dict_t * dict, char * key, uint64_t key_length, void * value)
Insert an entry into the dict.
The function allocates a new entry. If it was able to allocate AND insert the entry, the function returns 0. If either one failed, it will return -1 and the dict is left unchanged.
Warning
If a NULL pointer is passed, or if the dict has been deallocated, the function will crash.
Note
If the key is NULL some functions may break. Make sure it's not before calling the function.
Parameters
dict The dict in which to insert the entry.
key The key to refer to the value.
key_length The length of the key.
value The value refered at via the key.
Returns
0 on success, -1 on error.
Definition at line 12 of file dict_insert.c.
{
    uint32_t key_hash = 0;
    bucket_t **bucket_addr = NULL;
    if (DICT_MUST_GROW(dict) && -1 == dict_resize(dict))
        return -1;
    key_hash = murmurhash1(key, key_length, HASH_SEED);
    bucket_addr = &(dict->buckets[DICT_BUCKET_IDX(key_hash, dict->size)]);
    if (1 == dict_bucket_has_key(*bucket_addr, key) || \
        -1 == dict_bucket_insert(bucket_addr, key, value))
        return -1;
    ++dict->items;
    return 0;
}
References s_dict::buckets, dict_bucket_has_key(), DICT_BUCKET_IDX, dict_bucket_insert(), DICT_MUST_GROW, dict_resize(), HASH_SEED, s_dict::items, murmurhash1(), and s_dict::size.
dict_resize()
int dict_resize (dict_t * dict)
Resizes the dict.
This process implies that all the key hashes must be recomputed. Depending on both the size of the dict and the length of the keys, the runtime may be slow. We will used strlen instead of storing the length of the key as an entry member for the following reasons :
upon creation, there is a chance that the programmer already knows the length of the key, so that we don't have to use the strlen function. If they don't know the length of the key, they are responsible for using such function;
the resize opeartion is complitly abstract to the programmer;
dict object are pretty heavy in memory, it could be nice to save 8 bytes per key, knowning CPU can compute pretty fast, and that the strlen function is probably optimized;
Warning
If a NULL pointer is passed, or if the dict has been deallocated, the function will crash.
Note
If the dict could not be resized, it's unchanged and -1 is returned.
Parameters
dict The dict to resize.
Returns
0 on success, -1 on error.
Definition at line 85 of file dict_resize.c.
{
    uint64_t index = 0;
    uint64_t new_size = round_size(dict->size * DICT_RESIZE_FACTOR);
    bucket_t **new_buckets = compute_new_buckets(new_size);
    if (NULL == new_buckets)
        return -1;
    for (; index < dict->size; ++index)
        dict_rehash_bucket(dict->buckets[index], new_buckets, new_size);
    dict_buckets_dtor(dict->buckets, dict->size, NULL);
    free(dict->buckets);
    dict->buckets = new_buckets;
    dict->size = new_size;
    return 0;
}
References s_dict::buckets, compute_new_buckets(), dict_buckets_dtor(), dict_rehash_bucket(), DICT_RESIZE_FACTOR, round_size(), and s_dict::size.
Referenced by dict_insert().