Dict in C: src/dict_delete.c File Reference
dict_delete.c File Reference
#include <string.h>
#include "dict.h"
#include "murmurhash1.h"
Functions
int dict_delete (dict_t *dict, char *key, uint64_t key_length, free_pair_t free_pair)
Deletes an entry from the dict.
Function Documentation
dict_delete()
int dict_delete (dict_t * dict, char * key, uint64_t key_length, free_pair_t free_pair)
Deletes an entry from the dict.
The function tries to delete an entry based on the given key. If the key was not found, the function returns -1 as an error. If the entry is found, it's key and value are given as parameter of the free_pair function to let the programmer handle the memory release, if needed.
Warning
If dict or key is a NULL pointer, the function will crash.
Note
The key is not marked as const as it may get free'd by the free_pair function, but bear in mind the current function will not modify the key.
If the free_pair function is a NULL pointer, it's not called. It may be useful if neither the key nor the value were allocated.
Parameters
dict The dict from which the pair must be deleted.
key The key referring to the pair which must be deleted.
key_length The length of the key. If unknowned, use strlen(key).
free_pair The function called to release key and value memory.
Returns
0 on success, -1 on error.
Definition at line 12 of file dict_delete.c.
{
    uint32_t key_hash = 0;
    bucket_t **bucket_addr = NULL;
    if (DICT_MUST_SHRINK(dict) && -1 == dict_resize(dict))
        return -1;
    key_hash = murmurhash1(key, key_length, HASH_SEED);
    bucket_addr = &(dict->buckets[DICT_BUCKET_IDX(key_hash, dict->size)]);
    if (-1 == dict_bucket_delete(bucket_addr, key, free_pair))
        return -1;
    --dict->items;
    return 0;
}
References s_dict::buckets, dict_bucket_delete(), dict_resize(), s_dict::items, murmurhash1(), and s_dict::size.