Dict in C: include/murmurhash1.h File Reference
murmurhash1.h File Reference
#include <stdint.h>
Macros
#define R 16
#define M 0xc6a4a793
#define C sizeof(uint32_t)
Functions
uint32_t compute_padding (const uint8_t *data, uint64_t length, uint32_t h)
Computes the padding of the hash when it's length is not % uint32_t.
uint32_t murmurhash1 (const void *key, uint64_t length, uint32_t seed)
Hashes the key into an unsigned 32 bits.
Macro Definition Documentation
C
#define C sizeof(uint32_t)
Definition at line 16 of file murmurhash1.h.
Referenced by murmurhash1().
M
#define M 0xc6a4a793
Definition at line 15 of file murmurhash1.h.
Referenced by compute_padding(), and murmurhash1().
R
#define R 16
Definition at line 14 of file murmurhash1.h.
Referenced by compute_padding(), and murmurhash1().
Function Documentation
compute_padding()
uint32_t compute_padding (const uint8_t * data, uint64_t length, uint32_t h) inline
Computes the padding of the hash when it's length is not % uint32_t.
Parameters
data The remaining data to be processed.
length The remaning length of the data to be processed.
h The computed hash so far.
Returns
The new hash value.
Definition at line 13 of file murmurhash1.c.
{
    if (3 == length)
        h += data[2] << 16;
    if (2 <= length)
        h += data[1] << 8;
    if (1 <= length) {
        h += data[0];
        h *= M;
        h ^= h >> R;
    }
    return h;
}
References M, and R.
Referenced by murmurhash1().
murmurhash1()
uint32_t murmurhash1 (const void * key, uint64_t length, uint32_t seed) inline
Hashes the key into an unsigned 32 bits.
Parameters
key The key to hash.
length The length of the key.
seed The seed to use for the hash. Should be randomized once.
Returns
The hash result.
Definition at line 28 of file murmurhash1.c.
{
    uint32_t h = seed ^ (length * M);
    const uint8_t *data = (const uint8_t *) key;
    while (C <= length) {
        h += *(uint32_t *) data;
        h *= M;
        h ^= h >> R;
        data += C;
        length -= C;
    }
    h = compute_padding(data, length, h);
    h *= M;
    h ^= h >> 10;
    h *= M;
    h ^= h >> 17;
    return h;
}
References C, compute_padding(), M, and R.
Referenced by dict_delete(), dict_insert(), and dict_rehash_bucket().