name: "ci"

on:
    -   push

env:
    UNIT_TESTS: "./unit_tests"

jobs:
    run-tests:
        runs-on: "ubuntu-latest"
        container:
            image: "epitechcontent/epitest-docker:latest"
        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v4.1.1"
                with:
                    fetch-depth: 0

            -   name: "Run tests"
                timeout-minutes: 1
                run: "cmake -S . -B build && cmake --build build"

            -   name: "Run Valgrind"
                uses: "Ximaz/valgrind-action@v1.2.0"
                with:
                    binary_path: "./unit_tests"
